### ISSUE TITLE
Server.start() seems to never return while the server is started

### ISSUE THREAD

**Issue by zosrothko** [jbossas/jboss-as-maven-plugin#100]

**Comment by zosrothko** [comment]
Hi

Using jboss-as-plugin:start for starting a local standalone JBoss server seems to never give back hands to maven. This [log](https://github.com/jbossas/jboss-as-maven-plugin/files/2782832/mvn.log) is showing maven ending with an Build Failure with the exception 
```
[ERROR] Failed to execute goal org.jboss.as.plugins:jboss-as-maven-plugin:7.9.Final:start (startMI) on project mi: The server failed to start: Managed server was not started within [60] s -> [
Help 1]
```
while Jboss WildFly-11.0.0-Final has been really been started as displayed in the log.

Here the 
[pom.xml.txt](https://github.com/jbossas/jboss-as-maven-plugin/files/2782850/pom.xml.txt)
```
Z:\MXW\IC\MI\Tests>C:\ASF\apache-maven-3.5.4\bin\mvn -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: C:\ASF\apache-maven-3.5.4\bin\..
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_181\jre
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by jamezp** [comment]
This plugin is meant for JBoss EAP 6 and JBoss AS 7.x. For WildFly I'd suggest using the [WildFly Maven Plugin](https://docs.jboss.org/wildfly/plugins/maven/2.0.0.Final/).

**Comment by zosrothko** [comment]
Thank for the pointer, I did not search for a wildfly plugin. Sorry for the noise.
