### ISSUE TITLE
connection timed out

### ISSUE THREAD

**Issue by Erik1** [jbossas/jboss-as-maven-plugin#57]
jboss-cli.sh/.bat has the option to increase the waiting time for a given command to return with the parameter --timout. Increasing the time from 5000ms to 10000ms makes it possible to connect to one of my servers. 
It would be nice if the jboss-as-maven-plugin had 'timeout' as configuration option to for the goals like deploy, reploy, ... to solve "java.net.ConnectException: JBAS012144: Could not connect to remote://192.168.2.4:9999. The connection timed out"

**Comment by jamezp** [comment]
Fixed in #85
