### ISSUE TITLE
Allow specifying the name of the deployment file (would be renamed)

### ISSUE THREAD

**Issue by OndraZizka** [jbossas/jboss-as-maven-plugin#62]
Sometimes, eg. in test scenarios, the file to be uploaded ends up with some ugly name like foo-company-awesome-project-test-war-7.12.3213_2013-12-24.war. The derived context is then quite ugly. How about sparing the users creating an extra garbage in pom or project to set the context?

Adding a parameter like "deployAsFileName" which would simply rename (copy) the file before deploying would help.

WDYT?

**Comment by jamezp** [comment]
Just cleaning up issues and I this should work with the `filename` configuration property.
