### ISSUE TITLE
Allow jboss-as:redeploy not to fail when there's no deployment of that name

### ISSUE THREAD

**Issue by OndraZizka** [jbossas/jboss-as-maven-plugin#63]
In most scenarios, the user doesn't care if the app is or is not there. He just wants to have an app deployed.

Having to keep in mind whether to use :deploy or :redeploy is quite unpleasant.

Adding a parameter "force" to :redeploy would help.

:deploy already has "force" but AFAIK that doesn't overdeploy the app, just doesn't fail and keeps the old one. Or at least that's how it sounds from the docs:

"If force mode is disabled, the deploy goal will cause a build failure if the application being deployed already exists."
http://docs.jboss.org/jbossas/7/plugins/maven/latest/deploy-mojo.html

**Comment by jamezp** [comment]
Cleaning up issues and I think this should be solved.
