### ISSUE TITLE
Wait for redeploy to finish before ending "shutdown" goal

### ISSUE THREAD

**Issue by raphaeljolivet** [jbossas/jboss-as-maven-plugin#66]
Hi,

I am using jboss-maven-as-plugin in order to redploy my application before integration tests.
Since I often face the infamous PermGenSpace issue after a few redployments I need to restart the server before doing my deployment.

Sadly the "shutdown" goal won't wait for the server to actually restart.

Would it be possible to add an option in order for this goal not to return until the server is properly restarted ?

for more details, please see :
http://stackoverflow.com/questions/20956520/how-to-restart-jboss-with-maven-as-plugin-before-redeploy

**Comment by jamezp** [comment]
This will be fixed in 7.8.Final as part of https://issues.jboss.org/browse/JBASMP-73.
