### ISSUE TITLE
Deployment  issue- Server is running in domain mode, but no server groups have been defined

### ISSUE THREAD

**Issue by Jithinxavi** [jbossas/jboss-as-maven-plugin#75]
While deploying the app to Jboss domain mode, I'm getting this error - "Server is running in domain mode, but no server groups have been defined" , in deployment job I've already mentioned the "server- group" like this,

     settings.xml
                         <id>stg</id>
                        <properties>
                          <wildfly.id>stg</wildfly.id>
                          <wildfly.hostname><end-point></wildfly.hostname>
                          <wildfly.domain.serverGroup>other-server-group</wildfly.domain.serverGroup>
                        </properties>
                </profile>

Please help me to resolve this issue.

**Comment by jamezp** [comment]
You'll need to define the server group in the configuration.

```xml
<configuration>
    <domain>
        <server-groups>
            <server-group>${wildfly.domain.serverGroup}</server-group>
        </server-groups>
    </domain>
</configuration>
```

**Comment by jamezp** [comment]
Just cleaning up old issues.
