### ISSUE TITLE
After :deploy goal, the application hasn't been started - documentation of the <name> opt.

### ISSUE THREAD

**Issue by patoi** [jbossas/jboss-as-maven-plugin#77]
The 'application' has not been started after I've deployed the application with
```<name>application</name> ```
But when I changed the name to ```<name>application.war</name>``` , the application has been started.

I read the documentation and I found nothing about this naming requirements: https://docs.jboss.org/jbossas/7/plugins/maven/latest/deploy-mojo.html#name

Solution on the StackOverflow: http://stackoverflow.com/a/21009986/2231652

**Comment by jamezp** [comment]
I guess that could use some better documentation. It's essentially like passing the `--name` parameter on the `deploy` CLI command.

**Comment by jamezp** [comment]
Fixed upstream now, thanks for pointing that out.
