### ISSUE TITLE
Support for Gradle (and other) build tools

### ISSUE THREAD

**Issue by maxlinc** [jbossas/jboss-as-maven-plugin#90]
Maven remains popular, but there are many projects using Gradle, and many arguments for using it (see Dr. Dobb's [Why Build Your Java Projects with Gradle Rather than Ant or Maven?](http://www.drdobbs.com/jvm/why-build-your-java-projects-with-gradle/240168608) or [Gradle's features](https://gradle.org/maven_vs_gradle/)). This is especially true for devops tasks like creating JBoss deployment or configuration scripts, because Gradle is a more flexible scripting language, while Maven assumes a very specific lifecycle (building a java application).

It would be good if JBoss published official plugins for at least Maven & Gradle, and popular tools like SBT. The ZeroTurnaround [Java Tools and Technologies Survey](http://zeroturnaround.com/rebellabs/java-tools-and-technologies-landscape-for-2014/) can give you an idea which tools are popular.

The plugins are similar enough that they can share a "core" that does most of the work so maintaining several types of plugins is not too difficult. You can see an example of this on the [flyway](https://github.com/flyway/flyway) project, where there is a flyway-core, flyway-ant, flyway-maven, flyway-gradle, and flyway-sbt. So you could create a new project for gradle, but it would probably make sense to extract a "jboss-plugins-core" from this project, or to rename this project to "jboss-plugins" and have it build several.

**Comment by jamezp** [comment]
Sorry for the long delay. I've forgotten to check the issues here in quite some time it seems. FWIW only the https://github.com/wildfly/wildfly-maven-plugin will get new features at this point.

There's been some discussions around creating a Gradle plugin. I've also thought about creating a "core" project too, but I'm not sure how useful it would be. The biggest issue so far has just been I haven't had time to learn how to write a Gradle plugin :)

For the most part the plugin just uses API's from WildFly. The only think that would be useful in a core plugin I can think of is just some of a helper class to create operations. Though it's probably worth having a look at it.
